### ISSUE TITLE
Implement Automatic Language Selection at Application Startup

### ISSUE THREAD

**Issue by NidhalNaffati** [NidhalNaffati/hackathon-ramadan-2024#1]
### Description:

When our application launches, it should automatically retrieve the language setting from the settings.json file to uphold user preferences. This ensures a seamless experience for users, aligning with their language preferences from the moment they start the application.

### Objective:

To enable the application to read the language preference from settings.json upon startup, ensuring a personalized user experience from the outset.

**Comment by Scootu** [comment]
I put the default language to arabic , because we are targeting the arabic community , in i18n file

**Comment by NidhalNaffati** [comment]
I understand that Arabic is set as the default language. However, if the user changes the language, we must retain their selection as the new default language.

**Comment by Scootu** [comment]
Yes, of course
